# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: romeoebrahim
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./sls/config/env.yml)}
  iam:
    role: ${file(./sls/config/role.yml)}


package:
  individually: true

custom:
  cognito:
    PoolName: ${self:service}-${self:provider.stage}-UserPool

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
  - ${file(./sls/resources/MainTable.yml)}
